/* eslint-disable regexp/no-super-linear-backtracking */
/* eslint-disable no-control-regex */
/* eslint-disable redos/no-vulnerable */
import { env } from '@config';
import ms from 'ms';

export const ACCESS_EXPIRATION = ms(env.API.ACCESS_TOKEN.EXPIRATION);
export const REFRESH_EXPIRATION = ms(env.API.REFRESH_TOKEN.EXPIRATION);

export const CUSTOM_REGEX = {
	NAME: /^[\w',.\\-][^\d!#$%&()*+/:;<=>?@[\\\]_{|}~¡¿÷ˆ]{2,}$/,
	EMAIL: /^((([\w!#$%&'*+/=?\\^`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF-])+(\.([\w!#$%&'*+/=?\\^`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF-])+)*)|((")(((([\t ])*(\r\n))?([\t ])+)?(([\x01-\x08\v\f\x0e-\x1f!\x23-\x5b\x5d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*((([\t ])*(\r\n))?([\t ])+)?(")))@((([\da-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([\da-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([\w.\\~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF-])*([\da-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([\w.\\~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF-])*([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i,
	PASSWORD:
		/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!$%&*?@])[\d!$%&*?@A-Za-z]{8,}$/,
	MS: /^(\d+(.\d+)?((ms|[dhmswy])|(\s+(msec+(s)?|millisecond+(s)?|sec|second+(s)?|min+(s)?|minute+(s)?|hr+(s)?|hour+(s)?|day+(s)?|week+(s)?|yr+(s)?|year+(s)?))))+$/,
	BEARER_TOKEN: /^Bearer\s(.*)$/
};

export const ALLOWED_FILE_EXTENSIONS = {
	video: [
		'3g2',
		'3gp',
		'3gpp',
		'asf',
		'avi',
		'dat',
		'divx',
		'dv',
		'f4v',
		'flv',
		'm2ts',
		'm4v',
		'mkv',
		'mod',
		'mov',
		'mp4',
		'mpe',
		'mpeg',
		'mpeg4',
		'mpg',
		'mts',
		'nsv',
		'ogm',
		'ogv',
		'qt',
		'tod',
		'ts',
		'vob',
		'wmv'
	],
	image: [
		'bmp',
		'dib',
		'heic',
		'heif',
		'iff',
		'jfif',
		'jp2',
		'jpe',
		'jpeg',
		'jpg',
		'png',
		'psd',
		'tif',
		'tiff',
		'wbmp',
		'webp',
		'xbm'
	]
};
export const ALLOWED_FILE_MIMETYPES = {
	video: [
		'video/3gpp',
		'video/3gpp2',
		'video/h261',
		'video/h263',
		'video/h264',
		'video/jpeg',
		'video/jpm',
		'video/mj2',
		'video/mp4',
		'video/mpeg',
		'video/ogg',
		'video/quicktime',
		'video/vnd.dece.hd',
		'video/vnd.dece.mobile',
		'video/vnd.dece.pd',
		'video/vnd.dece.sd',
		'video/vnd.dece.video',
		'video/vnd.dvb.file',
		'video/vnd.fvt',
		'video/vnd.mpegurl',
		'video/vnd.ms-playready.media.pyv',
		'video/vnd.uvvu.mp4',
		'video/vnd.vivo',
		'video/webm',
		'video/x-f4v',
		'video/x-fli',
		'video/x-flv',
		'video/x-m4v',
		'video/x-matroska',
		'video/x-mng',
		'video/x-ms-asf',
		'video/x-ms-vob',
		'video/x-ms-wm',
		'video/x-ms-wmv',
		'video/x-ms-wmx',
		'video/x-ms-wvx',
		'video/x-msvideo',
		'video/x-sgi-movie',
		'video/x-smv'
	],
	image: [
		'image/bmp',
		'image/cgm',
		'image/g3fax',
		'image/gif',
		'image/ief',
		'image/jpeg',
		'image/ktx',
		'image/png',
		'image/prs.btif',
		'image/sgi',
		'image/svg+xml',
		'image/tiff',
		'image/vnd.adobe.photoshop',
		'image/vnd.dece.graphic',
		'image/vnd.djvu',
		'image/vnd.dvb.subtitle',
		'image/vnd.dwg',
		'image/vnd.dxf',
		'image/vnd.fastbidsheet',
		'image/vnd.fpx',
		'image/vnd.fst',
		'image/vnd.fujixerox.edmics-mmr',
		'image/vnd.fujixerox.edmics-rlc',
		'image/vnd.ms-modi',
		'image/vnd.net-fpx',
		'image/vnd.wap.wbmp',
		'image/vnd.xiff',
		'image/webp',
		'image/x-3ds',
		'image/x-cmu-raster',
		'image/x-cmx',
		'image/x-freehand',
		'image/x-icon',
		'image/x-mrsid-image',
		'image/x-pcx',
		'image/x-pict',
		'image/x-portable-anymap',
		'image/x-portable-bitmap',
		'image/x-portable-graymap',
		'image/x-portable-pixmap',
		'image/x-rgb',
		'image/x-tga',
		'image/x-xbitmap',
		'image/x-xpixmap',
		'image/x-xwindowdump'
	]
};
